OCS now checks that cscope is in $PATH

diff --git a/contrib/ocs b/contrib/ocs
--- a/contrib/ocs
+++ b/contrib/ocs
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Id:$
+# $Id: ocs,v 1.1 2000/04/21 23:36:26 hops1 Exp $
 # This utility maintains the database for cscope on a recursive dir set
 # Author:   donwo	Tue Jun 25 15:36:39 PDT 1996
 # Modified: hops Jan 2000  chg defaults to not update if files exist and force
@@ -70,9 +70,19 @@
 #
 # Here is where we put things
 
-CSCOPE=/usr/bin/cscope
+CSCOPE=cscope
 SYSDIR=/usr/local/lib/cs
 HOMEDIR=${HOME}/lib/cs
+
+# Check that cscope is in PATH
+type cscope 1>/dev/null 2>&1
+
+if [ $? -ne 0 ]
+then
+	echo "ERROR: cscope is not in \$PATH" >&2
+	echo "       Please set \$PATH correctly or make sure cscope is installed" >&2
+	exit 1
+fi
 
 # popup editor 
 #XCS_EDITOR=${HOME}/bin/x_cscope_editor
